# Generated by Django 5.2.8 on 2026-06-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_region', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMINISTRATEUR_SYSTEME', 'Administrateur Système'), ('SUPERVISEUR_DGI', 'Superviseur DGI'), ('AGENT_DGI', 'Agent DGI'), ('POLICE', 'Police'), ('CONTRIBUABLE', 'Contribuable')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('structure_id', models.IntegerField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20)),
                ('pays', models.CharField(default='NIGER', max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('type_vehicule', models.CharField(choices=[('VEHICULE', 'Véhicule'), ('MOTO', 'Moto')], max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('energie', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel')], max_length=20, null=True)),
                ('puissance_cv', models.IntegerField()),
                ('montant_taxe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_chassis', models.CharField(max_length=50, unique=True)),
                ('date_mise_circulation', models.DateField(null=True)),
                ('date_edition_carte_grise', models.DateField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='StatutVignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('VERT', 'Vert - Valide'), ('ORANGE', 'Orange - Échéance imminente'), ('ROUGE', 'Rouge - Expiré')], max_length=20)),
                ('date_debut_validite', models.DateField()),
                ('date_fin_validite', models.DateField()),
                ('code_securite', models.CharField(max_length=16, unique=True)),
                ('type_modification', models.CharField(choices=[('AUTOMATIQUE', 'Automatique'), ('MANUELLE', 'Manuelle')], max_length=20)),
                ('mobile_payment_ref', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='core.automobile')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='automobile',
            name='statut_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_auto', to='core.statutvignette'),
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('action_performee', models.TextField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='core.automobile')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=19, unique=True)),
                ('statut_usage', models.CharField(choices=[('ACTIF', 'Actif'), ('UTILISE', 'Utilisé')], default='ACTIF', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to='core.automobile')),
                ('generateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='automobile',
            unique_together={('immatriculation', 'region')},
        ),
    ]
