# Generated by Django 5.2.8 on 2026-06-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operateur', models.CharField(choices=[('NITA', 'NITA'), ('AMANATA', 'Amanata'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=20)),
                ('date_initiation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.automobile')),
                ('statut_vignette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='core.statutvignette')),
            ],
        ),
    ]
