# Generated by Django 5.2.8 on 2026-06-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='otp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='core.otpverification'),
        ),
    ]
