# Generated by Django 5.2.8 on 2026-06-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paiement_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
