# Generated by Django 5.2.8 on 2026-06-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parametreplateforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.region'),
        ),
    ]
