# Generated by Django 5.2.8 on 2026-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_utilisateur_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(choices=[('NITA', 'NITA'), ('AMANATA', 'Amanata'), ('ORANGE_MONEY', 'ZamaniCash'), ('AIRTEL_MONEY', 'Airtel Money')], max_length=20),
        ),
    ]
