# Generated by Django 5.2.8 on 2026-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_plainte_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='duree_annees',
            field=models.IntegerField(default=1),
        ),
    ]
