# Generated by Django 5.2.8 on 2026-07-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_format_immatriculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='carte_expiration',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='paiement',
            name='carte_numero_masque',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(choices=[('NITA', 'NITA'), ('AMANATA', 'Amanata'), ('ORANGE_MONEY', 'ZamaniCash'), ('AIRTEL_MONEY', 'Airtel Money'), ('CARTE_BANCAIRE', 'Carte bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
