# Generated by Django 5.2.8 on 2026-07-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_paiement_carte_expiration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobile',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom_region']},
        ),
    ]
