# Generated by Django 5.2.8 on 2026-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_automobile_carte_grise_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automobile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='immatriculation',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
